#! /bin/bash
if (( $# == 2 ))
then

old_suffix=$1
new_suffix=$2
    
for f in *.$old_suffix

if [[ -e /s/chopin/g/under/shamraev/${f%.*}.$new_suffix ]]
then
    echo "ERROR! A file with such name already exists." >&2
    else
do
    new_name=${f%.*}.$new_suffix
    echo Rename $f to $new_name
    done
else
    echo "ERROR! ENTER 2 ARGUMENTS. NOT MORE NOT LESS." >&2
    exit 1

fi
